export const UNCLASSIFIED_INDUSTRY = '未分类';

const INDUSTRY_BY_SYMBOL: Record<string, string> = {
  'NVDA.US': '半导体',
  'AMD.US': '半导体',
  'AVGO.US': '半导体',
  'INTC.US': '半导体',
  'TSM.US': '半导体',
  'ASX.US': '半导体',
  'AMKR.US': '半导体',
  'SMH.US': '半导体',
  'SOXL.US': '半导体',
  'MU.US': '存储',
  'MUU.US': '存储',
  'SNDK.US': '存储',
  'DISK.US': '存储',
  'DRAM.US': '存储',
  'SKHY.US': '存储',
  'SKHYV.US': '存储',
  'SNK.US': '存储',
  'SNXX.US': '存储',
  'RAM.US': '存储',
  'MRVL.US': '半导体',
  '7709.HK': '存储',
  'AAPL.US': '巨头',
  'MSFT.US': '巨头',
  'GOOG.US': '巨头',
  'GOOGL.US': '巨头',
  'AMZN.US': '巨头',
  'TSLA.US': '巨头',
  'ORCL.US': '软件云',
  'NOW.US': '软件云',
  'NET.US': '软件云',
  'NBIS.US': '软件云',
  'INFQ.US': '软件云',
  'ASTS.US': '航天',
  'RKLB.US': '航天',
  'RKLX.US': '航天',
  'SPCH.US': '航天',
  'SPCX.US': '航天',
  'KO.US': '消费',
  'PEP.US': '消费',
  'MCD.US': '消费',
  'VST.US': '能源电力',
  'QQQM.US': '大盘 ETF',
  'VOO.US': '大盘 ETF',
  'SPY.US': '大盘 ETF',
  'SCHD.US': '大盘 ETF',
  'VXX.US': '波动率',
  'UVIX.US': '波动率',
  'SGOV.US': '现金类',
  'SHV.US': '现金类',
  'USFR.US': '现金类',
  'ICSH.US': '现金类',
};

export function industryOf(symbol: string): string {
  return INDUSTRY_BY_SYMBOL[symbol] ?? UNCLASSIFIED_INDUSTRY;
}
